import httpx
from app.core.config import settings
from app.models.profile_model import Profile

class AIService:
    @staticmethod
    def build_system_prompt(profile: Profile) -> str:
        concerns = ", ".join(profile.skin_concerns) if profile.skin_concerns else "None specified"
        allergies = ", ".join(profile.known_allergies) if profile.known_allergies else "None"
        
        return (
            f"You are KINDGLOW, an expert dermatological and skincare AI assistant. "
            f"Tailor all recommendations strictly to the user's personal skin profile:\n"
            f"- Skin Type: {profile.skin_type}\n"
            f"- Primary Concerns: {concerns}\n"
            f"- Climate: {profile.climate or 'Not specified'}\n"
            f"- Age Group: {profile.age_group or 'Not specified'}\n"
            f"- Known Allergies/Sensitivities: {allergies}\n\n"
            f"Provide safe, clear, and actionable skincare advice. Strictly avoid recommending ingredients that conflict with their allergies."
        )

    async def generate_response(self, prompt: str, profile: Profile) -> str:
        system_prompt = self.build_system_prompt(profile)
        
        # Get configured model name (fallback to gemma3:4b)
        model_name = getattr(settings, "OLLAMA_MODEL", getattr(settings, "AI_DEFAULT_MODEL", "gemma3:4b"))
        
        payload = {
            "model": model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            "stream": False
        }

        try:
            async with httpx.AsyncClient(timeout=180.0) as client:
                response = await client.post(
                    f"{settings.OLLAMA_BASE_URL}/api/chat",
                    json=payload
                )
                
                if response.status_code == 200:
                    data = response.json()
                    # Safe extraction of message content from Ollama response
                    message = data.get("message", {})
                    content = message.get("content", "")
                    if content:
                        return content
                    return "No response content generated by the model."
                else:
                    error_msg = f"Ollama HTTP {response.status_code}: {response.text}"
                    print(f"❌ {error_msg}")
                    return error_msg
                    
        except httpx.ConnectError as exc:
            print(f"❌ Connection Error: Unable to connect to Ollama at {settings.OLLAMA_BASE_URL}")
            return "Error: Unable to connect to Ollama. Ensure Ollama is running (`ollama serve`)."
            
        except Exception as e:
            # Print full exception details in server console for easy debugging
            import traceback
            print("❌ Exception occurred during AI generation:")
            traceback.print_exc()
            return f"An unexpected error occurred: {type(e).__name__} - {str(e)}"